/* Auto-generated by genmsg_cpp for file /home/eric/groovy_workspace/Olin_AR_Drone/ethzasl_ptam/ptam_com/srv/PointCloud.srv */
#ifndef PTAM_COM_SERVICE_POINTCLOUD_H
#define PTAM_COM_SERVICE_POINTCLOUD_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"



#include "sensor_msgs/PointCloud2.h"

namespace ptam_com
{
template <class ContainerAllocator>
struct PointCloudRequest_ {
  typedef PointCloudRequest_<ContainerAllocator> Type;

  PointCloudRequest_()
  : flags(0)
  {
  }

  PointCloudRequest_(const ContainerAllocator& _alloc)
  : flags(0)
  {
  }

  typedef uint32_t _flags_type;
  uint32_t flags;


  typedef boost::shared_ptr< ::ptam_com::PointCloudRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ptam_com::PointCloudRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PointCloudRequest
typedef  ::ptam_com::PointCloudRequest_<std::allocator<void> > PointCloudRequest;

typedef boost::shared_ptr< ::ptam_com::PointCloudRequest> PointCloudRequestPtr;
typedef boost::shared_ptr< ::ptam_com::PointCloudRequest const> PointCloudRequestConstPtr;


template <class ContainerAllocator>
struct PointCloudResponse_ {
  typedef PointCloudResponse_<ContainerAllocator> Type;

  PointCloudResponse_()
  : pointcloud()
  {
  }

  PointCloudResponse_(const ContainerAllocator& _alloc)
  : pointcloud(_alloc)
  {
  }

  typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _pointcloud_type;
   ::sensor_msgs::PointCloud2_<ContainerAllocator>  pointcloud;


  typedef boost::shared_ptr< ::ptam_com::PointCloudResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ptam_com::PointCloudResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PointCloudResponse
typedef  ::ptam_com::PointCloudResponse_<std::allocator<void> > PointCloudResponse;

typedef boost::shared_ptr< ::ptam_com::PointCloudResponse> PointCloudResponsePtr;
typedef boost::shared_ptr< ::ptam_com::PointCloudResponse const> PointCloudResponseConstPtr;

struct PointCloud
{

typedef PointCloudRequest Request;
typedef PointCloudResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct PointCloud
} // namespace ptam_com

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ptam_com::PointCloudRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ptam_com::PointCloudRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ptam_com::PointCloudRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1849b0a9671ee16706c8c3de706e78bd";
  }

  static const char* value(const  ::ptam_com::PointCloudRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1849b0a9671ee167ULL;
  static const uint64_t static_value2 = 0x06c8c3de706e78bdULL;
};

template<class ContainerAllocator>
struct DataType< ::ptam_com::PointCloudRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ptam_com/PointCloudRequest";
  }

  static const char* value(const  ::ptam_com::PointCloudRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ptam_com::PointCloudRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint32 flags\n\
\n\
";
  }

  static const char* value(const  ::ptam_com::PointCloudRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::ptam_com::PointCloudRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ptam_com::PointCloudResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ptam_com::PointCloudResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ptam_com::PointCloudResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "56680b720436a8fbd002ea7abe6966e1";
  }

  static const char* value(const  ::ptam_com::PointCloudResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x56680b720436a8fbULL;
  static const uint64_t static_value2 = 0xd002ea7abe6966e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::ptam_com::PointCloudResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ptam_com/PointCloudResponse";
  }

  static const char* value(const  ::ptam_com::PointCloudResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ptam_com::PointCloudResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "sensor_msgs/PointCloud2 pointcloud\n\
\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointCloud2\n\
# This message holds a collection of N-dimensional points, which may\n\
# contain additional information such as normals, intensity, etc. The\n\
# point data is stored as a binary blob, its layout described by the\n\
# contents of the \"fields\" array.\n\
\n\
# The point cloud data may be organized 2d (image-like) or 1d\n\
# (unordered). Point clouds organized as 2d images may be produced by\n\
# camera depth sensors such as stereo or time-of-flight.\n\
\n\
# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n\
# points).\n\
Header header\n\
\n\
# 2D structure of the point cloud. If the cloud is unordered, height is\n\
# 1 and width is the length of the point cloud.\n\
uint32 height\n\
uint32 width\n\
\n\
# Describes the channels and their layout in the binary data blob.\n\
PointField[] fields\n\
\n\
bool    is_bigendian # Is this data bigendian?\n\
uint32  point_step   # Length of a point in bytes\n\
uint32  row_step     # Length of a row in bytes\n\
uint8[] data         # Actual point data, size is (row_step*height)\n\
\n\
bool is_dense        # True if there are no invalid points\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointField\n\
# This message holds the description of one point entry in the\n\
# PointCloud2 message format.\n\
uint8 INT8    = 1\n\
uint8 UINT8   = 2\n\
uint8 INT16   = 3\n\
uint8 UINT16  = 4\n\
uint8 INT32   = 5\n\
uint8 UINT32  = 6\n\
uint8 FLOAT32 = 7\n\
uint8 FLOAT64 = 8\n\
\n\
string name      # Name of field\n\
uint32 offset    # Offset from start of point struct\n\
uint8  datatype  # Datatype enumeration, see above\n\
uint32 count     # How many elements in the field\n\
\n\
";
  }

  static const char* value(const  ::ptam_com::PointCloudResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ptam_com::PointCloudRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.flags);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PointCloudRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ptam_com::PointCloudResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.pointcloud);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PointCloudResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<ptam_com::PointCloud> {
  static const char* value() 
  {
    return "5f22ae501f068f11fc397cb230046acc";
  }

  static const char* value(const ptam_com::PointCloud&) { return value(); } 
};

template<>
struct DataType<ptam_com::PointCloud> {
  static const char* value() 
  {
    return "ptam_com/PointCloud";
  }

  static const char* value(const ptam_com::PointCloud&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<ptam_com::PointCloudRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5f22ae501f068f11fc397cb230046acc";
  }

  static const char* value(const ptam_com::PointCloudRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<ptam_com::PointCloudRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ptam_com/PointCloud";
  }

  static const char* value(const ptam_com::PointCloudRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<ptam_com::PointCloudResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5f22ae501f068f11fc397cb230046acc";
  }

  static const char* value(const ptam_com::PointCloudResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<ptam_com::PointCloudResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ptam_com/PointCloud";
  }

  static const char* value(const ptam_com::PointCloudResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // PTAM_COM_SERVICE_POINTCLOUD_H

