/* Auto-generated by genmsg_cpp for file /home/eric/groovy_workspace/Olin_AR_Drone/ethzasl_ptam/ptam_com/msg/KeyFrame_msg.msg */
#ifndef PTAM_COM_MESSAGE_KEYFRAME_MSG_H
#define PTAM_COM_MESSAGE_KEYFRAME_MSG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "geometry_msgs/PoseWithCovarianceStamped.h"

namespace ptam_com
{
template <class ContainerAllocator>
struct KeyFrame_msg_ {
  typedef KeyFrame_msg_<ContainerAllocator> Type;

  KeyFrame_msg_()
  : KFids()
  , KFs()
  {
  }

  KeyFrame_msg_(const ContainerAllocator& _alloc)
  : KFids(_alloc)
  , KFs(_alloc)
  {
  }

  typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _KFids_type;
  std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  KFids;

  typedef std::vector< ::geometry_msgs::PoseWithCovarianceStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PoseWithCovarianceStamped_<ContainerAllocator> >::other >  _KFs_type;
  std::vector< ::geometry_msgs::PoseWithCovarianceStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PoseWithCovarianceStamped_<ContainerAllocator> >::other >  KFs;


  typedef boost::shared_ptr< ::ptam_com::KeyFrame_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ptam_com::KeyFrame_msg_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct KeyFrame_msg
typedef  ::ptam_com::KeyFrame_msg_<std::allocator<void> > KeyFrame_msg;

typedef boost::shared_ptr< ::ptam_com::KeyFrame_msg> KeyFrame_msgPtr;
typedef boost::shared_ptr< ::ptam_com::KeyFrame_msg const> KeyFrame_msgConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ptam_com::KeyFrame_msg_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ptam_com::KeyFrame_msg_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ptam_com

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ptam_com::KeyFrame_msg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ptam_com::KeyFrame_msg_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ptam_com::KeyFrame_msg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d865cbd185d5633ac1d50184eb2a3461";
  }

  static const char* value(const  ::ptam_com::KeyFrame_msg_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd865cbd185d5633aULL;
  static const uint64_t static_value2 = 0xc1d50184eb2a3461ULL;
};

template<class ContainerAllocator>
struct DataType< ::ptam_com::KeyFrame_msg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ptam_com/KeyFrame_msg";
  }

  static const char* value(const  ::ptam_com::KeyFrame_msg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ptam_com::KeyFrame_msg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint32[]   KFids\n\
geometry_msgs/PoseWithCovarianceStamped[]   KFs\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseWithCovarianceStamped\n\
# This expresses an estimated pose with a reference coordinate frame and timestamp\n\
\n\
Header header\n\
PoseWithCovariance pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseWithCovariance\n\
# This represents a pose in free space with uncertainty.\n\
\n\
Pose pose\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::ptam_com::KeyFrame_msg_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ptam_com::KeyFrame_msg_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.KFids);
    stream.next(m.KFs);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct KeyFrame_msg_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ptam_com::KeyFrame_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ptam_com::KeyFrame_msg_<ContainerAllocator> & v) 
  {
    s << indent << "KFids[]" << std::endl;
    for (size_t i = 0; i < v.KFids.size(); ++i)
    {
      s << indent << "  KFids[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.KFids[i]);
    }
    s << indent << "KFs[]" << std::endl;
    for (size_t i = 0; i < v.KFs.size(); ++i)
    {
      s << indent << "  KFs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PoseWithCovarianceStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.KFs[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // PTAM_COM_MESSAGE_KEYFRAME_MSG_H

