/* Auto-generated by genmsg_cpp for file /home/eric/groovy_workspace/Olin_AR_Drone/ethzasl_ptam/ptam_com/msg/Vector3Array.msg */
#ifndef PTAM_COM_MESSAGE_VECTOR3ARRAY_H
#define PTAM_COM_MESSAGE_VECTOR3ARRAY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "geometry_msgs/Vector3.h"

namespace ptam_com
{
template <class ContainerAllocator>
struct Vector3Array_ {
  typedef Vector3Array_<ContainerAllocator> Type;

  Vector3Array_()
  : header()
  , vector3()
  {
  }

  Vector3Array_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , vector3(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Vector3_<ContainerAllocator> >::other >  _vector3_type;
  std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Vector3_<ContainerAllocator> >::other >  vector3;


  typedef boost::shared_ptr< ::ptam_com::Vector3Array_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ptam_com::Vector3Array_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Vector3Array
typedef  ::ptam_com::Vector3Array_<std::allocator<void> > Vector3Array;

typedef boost::shared_ptr< ::ptam_com::Vector3Array> Vector3ArrayPtr;
typedef boost::shared_ptr< ::ptam_com::Vector3Array const> Vector3ArrayConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ptam_com::Vector3Array_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ptam_com::Vector3Array_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ptam_com

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ptam_com::Vector3Array_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ptam_com::Vector3Array_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ptam_com::Vector3Array_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7bf65100ecb1863f26514d20169e41a1";
  }

  static const char* value(const  ::ptam_com::Vector3Array_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x7bf65100ecb1863fULL;
  static const uint64_t static_value2 = 0x26514d20169e41a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::ptam_com::Vector3Array_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ptam_com/Vector3Array";
  }

  static const char* value(const  ::ptam_com::Vector3Array_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ptam_com::Vector3Array_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
geometry_msgs/Vector3[] vector3\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::ptam_com::Vector3Array_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::ptam_com::Vector3Array_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::ptam_com::Vector3Array_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ptam_com::Vector3Array_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.vector3);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Vector3Array_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ptam_com::Vector3Array_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ptam_com::Vector3Array_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vector3[]" << std::endl;
    for (size_t i = 0; i < v.vector3.size(); ++i)
    {
      s << indent << "  vector3[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "    ", v.vector3[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // PTAM_COM_MESSAGE_VECTOR3ARRAY_H

